name: VK Auto Cleaner

on:
  schedule:
    - cron: '0 3 * * *' # Запуск в 3 утра
  workflow_dispatch: # Ручной запуск

jobs:
  run-cleaner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install vk_api requests python-dateutil

      - name: Run script
        env:
          VK_TOKEN: ${{ secrets.VK_TOKEN }}
        run: python main.py
